blog/urls.py
from django.urls import include, path
from blog import views

urlpatterns = [
    path('accueil/', views.accueil, name='accueil'),
    path('<slug>', views.lire_article, name='blog_lire'),
]

crepes/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]






# """crepes URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

blog/models.py
from django.db import models

class Article(models.Model):
    titre = models.CharField(max_length=100)
    slug = models.SlugField()
    auteur = models.CharField(max_length=42)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(verbose_name="Date de parution",
                                auto_now_add=True, auto_now=False)
    is_visible = models.BooleanField(verbose_name="Article publié ?",
                                     default=False)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE)

    def __str__(self):
        return self.titre

    # En cas de besoin, vous êtes autorisé à rajouter des méthodes ou
    # propriétés dans ce modèle.


class Categorie(models.Model):
    titre = models.CharField(max_length=100)

    def __str__(self):
        return self.titre


class Comment(models.Model):
    pseudo      = models.CharField(max_length=50)
    mail        = models.EmailField(max_length=254) 
    content     = models.TextField(null=True)
    date        = models.DateTimeField(verbose_name="Date de publication", auto_now_add=True, auto_now=False)
    is_visible  = models.BooleanField(verbose_name="Le commentaire est visible ?", default=True)
    article     = models.ForeignKey('Article', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Commentaire"
        ordering = ['date']

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.Form):
   pseudo =		forms.CharField(max_length=50, label="Pseudo")
   mail = 		forms.EmailField(max_length=254, label="Email") 
   content = 	forms.CharField(widget=forms.Textarea, label="Contenu")

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, Comment
from .forms import CommentForm


def accueil(request):
    """
    Affiche les 5 derniers articles du blog. Nous n'avons pas encore
    vu comment faire de la pagination, donc on ne donne pas la
    possibilité de lire les articles plus vieux via l'accueil pour
    le moment.
    """
    articles = Article.objects.filter(is_visible=True).order_by('-date')[:4]

    return render(request, 'blog/accueil.html', {'articles': articles})


def lire_article(request, slug):
    """
    Affiche un article complet, sélectionné en fonction du slug
    fourni en paramètre
    """
    article    = get_object_or_404(Article, slug=slug)
    comments    = Comment.objects.filter(is_visible=True, article=article).order_by('-date')[:4]   
    form        = CommentForm(request.POST or None)

    if form.is_valid():
        comment             = Comment()
        comment.pseudo      = form.cleaned_data['pseudo']
        comment.mail        = form.cleaned_data['mail']
        comment.content     = form.cleaned_data['content']
        comment.article     = article
        comment.save()
        return redirect('/blog/' + slug)

    return render(request, 'blog/lire_article.html', locals())

blog/templates/blog/accueil.html
{% extends "blog/base.html" %}

{% block title %}Accueil du blog{% endblock %}

{% block content %}
	<h1>Derniers articles</h1>

	{% for article in articles %}
		<h2 class="titre-article">{{ article.titre }}</h2>
			
		<p class="infos-article">Le {{ article.date|date:'SHORT_DATETIME_FORMAT' }}, 
		{% if 0 == article.comment_set.count %}
			Pas de commentaire pour le moment.
		{% else %}
			{{ article.comment_set.count }} commentaire{{ article.comment_set.count|pluralize }}.</p>
		{% endif %}

		<div class="contenu-article">
			{{ article.contenu|safe|truncatewords_html:30 }}
		</div>

		<p><a href="{% url 'blog_lire' article.slug %}">Lire la suite</a></p>

		<hr />
	{% endfor %}

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
    <title>{% block title %}Mon blog{% endblock %} - Crêpes bretonnes</title>
    
    <link rel="stylesheet" href="{% static 'blog/styles.css' %}" />
</head>

<body>
    <header>
    	<aside>
        	<a href="{% url 'admin:index' %}">Admin</a>
        </aside>

        <h1>Crêpes-bretonnes.com</h1>
    </header>

    <div class="container">
    	{% block content %}{% endblock %}
    </div>
            
    <footer>
        Mon super blog - Powered by Django
    </footer>
</body>
</html>

blog/templates/blog/lire_article.html
{% extends "blog/base.html" %}

{% block title %}{{ article.titre }}{% endblock %}

{% block content %}

	<p>
		<a href="{% url 'accueil' %}">Retour à la liste des articles</a>
	</p>

	<h2 class="titre-article">{{ article.titre }}</h2>
	<p class="infos-article">Par {{ article.auteur }}, le {{ article.date }}</p>

	<div class="contenu-article">
		{{ article.contenu|safe }}
	</div>

	<h3 class="titre-comments">Commentaires</h3>

	<h4>Poster votre propre commentaire</h4>
	<form method="post" action="{% url 'blog_lire' article.slug %}" class="pure-form">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<inoput type="hidden" name="article" id="id_article" value="{{ article.id }}">
		<p style="text-align:center">
			<input class="pure-button pure-button-primary" type="submit" />
		</p>
	</form>

	<div class="clear"></div>

	<div class="commentaire">
		{% for comment in comments %}
			<p>{{ comment.pseudo }}, le {{ comment.date }}<br>
			<p>{{ comment.content }}</p>
			<br>
		{% endfor %}
	</div>

{% endblock %} 